version: "3.9"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
    ports:
      - "8989:8989"
    volumes:
      - /data/appdata/sonarr/config:/config
      - /data/:/data
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
    ports:
      - "6767:6767"
    volumes:
      - /data/:/data
      - /data/appdata/bazarr/config:/config
    restart: unless-stopped
  overseerr:
    container_name: overseerr
    image: linuxserver/overseerr:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
    ports:
      - "5055:5055"
    volumes:
      - /data/appdata/overseerr/config:/config
    restart: unless-stopped
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
      - VERSION=docker
      #- PLEX_CLAIM=claim-GxuYxt2Ks2NbyWkX4uyC
    network_mode: host
   # ports:
   #   - "32400:32400/tcp"
   #   - "3005:3005/tcp"
   #   - "32469:32469/tcp"
   #   - "1900:1900/udp"
   #   - "32410:32410/udp"
   #   - "32412:32412/udp"
   #   - "32413:32413/udp"
   #   - "32414:32414/udp"
    volumes:
      - /data/appdata/plex/config/:/config
      - /data/media/:/data/media
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
    ports:
      - "9696:9696"
    volumes:
      - /data/appdata/prowlarr/config:/config
    restart: unless-stopped
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
      - UMASK=002
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /data/appdata/qbittorrent/config:/config
      - /data:/data
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Lisbon
    ports:
      - "7878:7878"
    volumes:
      - /data/appdata/radarr/config:/config
      - /data/:/data
    restart: unless-stopped
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - "3000:3000"
    volumes:
      - /data/appdata/homepage/config:/config
