//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CamadaInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background Color:.
        /// </summary>
        internal static string ABOUT_LABEL_BACKGROUNDCOLOR {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_BACKGROUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2024 Ricardo Moura, All rights reserved..
        /// </summary>
        internal static string ABOUT_LABEL_COPYRIGHT {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font:.
        /// </summary>
        internal static string ABOUT_LABEL_FONT {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        internal static string ABOUT_LABEL_NAME {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        internal static string ABOUT_LABEL_NUMBER {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto Final.
        /// </summary>
        internal static string ABOUT_LABEL_SUBTITLE {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text Color:.
        /// </summary>
        internal static string ABOUT_LABEL_TEXTCOLOR {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_TEXTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programação Orientada a Objetos.
        /// </summary>
        internal static string ABOUT_LABEL_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricardo Moura.
        /// </summary>
        internal static string ABOUT_TEXTBOX_NAME {
            get {
                return ResourceManager.GetString("ABOUT_TEXTBOX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a22309442.
        /// </summary>
        internal static string ABOUT_TEXTBOX_NUMBER {
            get {
                return ResourceManager.GetString("ABOUT_TEXTBOX_NUMBER", resourceCulture);
            }
        }
    }
}
